#!/usr/bin/env ruby
# Rake tasks to start/stop Logstash
#
# This is essentially a modified copy of the solr.rake
# which is distributed alongside acts_as_solr
require 'rubygems'
require 'rake'
require 'net/http'
require 'rbconfig'

namespace :logstash do
  # See http://cookbook.logstash.net/recipes/using-upstart/ for running logstash as a service.
  desc 'Starts Logstash. Options accepted: CONF=your_logstash_config.'
  task :start do
      LOGSTASH_PATH = "logstash-1.2.1-flatjar.jar"
      CONF_PATH = "./config/"
      CONF_FILE = ENV["CONF"] || "ezproxy.conf"
      LOGSTASH_LOGPATH = "./agent-log/"
      LOGSTASH_LOGFILE = "logstash." + Time.now.strftime("%F") + ".log"
    #begin
        puts "Loading ElasticSearch index template."
        cmd = "#{CONF_PATH}es_templates/default_template.sh"
        
        temp_pid = Process.spawn(cmd)
        Process.wait(temp_pid)
        puts "Loaded index template."
    #rescue Exception => e
    #  puts e.inspect
    #end
    begin
      pid = start_logstash
      Process.detach pid
    rescue Exception => e
        puts e.inspect
    end
  end

  def start_logstash
       # Startup Logstash with conf file
      conf = CONF_PATH + CONF_FILE
      puts "\n Using config = #{conf}"
      puts "Starting Logstash"
      cmd = "java -XX:MaxHeapSize=512m -jar #{LOGSTASH_PATH} agent --pluginpath ./plugins -f #{CONF_PATH}#{CONF_FILE} -l #{LOGSTASH_LOGPATH}#{LOGSTASH_LOGFILE}"
      puts cmd
      pid = Process.spawn(cmd) 
      puts "Logstash started with pid #{pid.to_s}"
      pid
    rescue e
      puts e.inspect
  end
end 
